version: '3'

services:
  web-app: &web-app-config
    build:
      context: .
      dockerfile: ./Dockerfile
    command: flask run --host=0.0.0.0
    environment:
      DB_CONN_URL: postgresql+psycopg2://user:password@pg:5432/postgres
      FLASK_ENV: developmet
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - pg
#      pg:
#        condition: service_healthy

  web-app-prod:
    <<: *web-app-config
    environment:
      DB_CONN_URL: postgresql+psycopg2://user:password@pg:5432/postgres
      FLASK_ENV: production

  pg:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready postgres -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
